# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Build and Test AutoSD

on:
  pull_request:
    paths:
      - 'reference_integration/**'
  workflow_dispatch:

jobs:
  lola-demo:
    name: lola-demo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.9.1

      - name: Install System Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y podman curl qemu-system

      - name: Pre Build Actions
        run: |
          cp ../vars-devel.yml vars-devel.yml
          cp ../vars.yml vars.yml
        working-directory: reference_integration/build/lola_demo

      - name: Build AutoSD Image
        uses: ./.github/actions/aib
        with:
          manifest: lola-demo.aib.yml
          distro: autosd10
          mode: package
          target: qemu
          export: qcow2
          extra_args: '--define-file vars-devel.yml --define-file vars.yml'
          disk_path: disk.qcow2
          base_dir: reference_integration/build/lola_demo

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Test QEMU image
        run: |
          sshcmd() {
            sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 2222 root@localhost $@
          }
          ../../scripts/run_qemu disk.qcow2
          sleep 5
          sshcmd 'cat /etc/os-release'
          sleep 10
          sshcmd 'bluechictl start agent-qm lola-ipc-sub.service'
          sleep 5
          sshcmd '/usr/local/bin/lola-ipc-test'
        env:
          SSH_PASSWORD: password
        working-directory: reference_integration/build/lola_demo
